cache: packages
sudo: required
warnings_are_errors: false
services:
  - docker
# database setup
before_install:
  # Set up environment and create required images
  # If no error don't print output
  - docker-compose ps
script:
  # Load packages and install the required packages
  # Install retriever from source and run tests
  - docker-compose run -e NOT_CRAN=true rdata /bin/sh -c 'Rscript load_and_test.R'
